unbind C-b
set -g prefix C-space 

unbind '"'
bind \\ split-window -h

unbind '%'
bind - split-window -v

unbind Up
unbind Down
unbind Left
unbind Right

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind z
bind m resize-pane -Z

